server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: postgres
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
