server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
